- name: Set Ip Loobpack
  hosts: all
  gather_facts: no

  tasks:
    - name: Set loopback IPv4 address
      ios_loopback:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
      with_items:
        - { name: loopback 0, ipv4: " 192.168.5.1/24 " }
        - { name: loopback 1, ipv4: " 192.168.5.2/24 " }
        - { name: loopback 2, ipv4: " 192.168.5.3/24 " }

      - name: show interface loopback
        ios_command:
          - show interface loopback
        register: show_interface_loopback

      - debug: var=show_interface_loopback.stdout_lines

        
        